---
title: Anton's Website
timezone: Europe/Moscow
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: true
    share: true
    related: true
- scope:
    path: _pages
    type: pages
  values:
    layout: single
    author_profile: true
- scope:
    path: ''
    type: docs
  values:
    layout: single
    read_time: false
    author_profile: false
    share: false
    comments: false
    sidebar:
      nav: docs
- scope:
    path: ''
    type: recipes
  values:
    layout: single
    author_profile: true
    share: true
    comments: true
- scope:
    path: ''
    type: pets
  values:
    layout: single
    author_profile: true
    share: true
    comment: true
- scope:
    path: ''
    type: portfolio
  values:
    layout: single
    author_profile: false
    share: true
minimal_mistakes_skin: default
repository: mmistakes/minimal-mistakes
remote_theme: mmistakes/minimal-mistakes
locale: en-US
title_separator: "-"
name: Anton Karazeev
description: Anton's Website
url: https://akarazeev.github.io
baseurl: ''
teaser: 
words_per_minute: 200
comments:
  provider: disqus
  disqus:
    shortname: https-akarazeev-github-io
search: false
google_site_verification: yC27Uiv932X1t3mxBkUyluvBa9whNH-xs0iNiWTpmD8
twitter:
  username: antonkarazeev
facebook:
  username: anton.karazeev
linkedin:
  username: akarazeev
youtube:
  username: https://www.youtube.com/c/AntonKarazeev
soundcloud:
  username: anton-karazeev
instagram:
  username: akarazeev
stackoverflow:
  username: 5080068/anton-karazeev
github:
- meta
og_image: "/assets/images/site-logo.jpg"
social:
  type: 
  name: 
  links:
  - https://twitter.com/antonkarazeev
  - https://facebook.com/anton.karazeev
  - https://in.linkedin.com/in/akarazeev
  - http://youtube.com/c/AntonKarazeev
  - http://github.com/akarazeev
analytics:
  provider: google-universal
  google:
    tracking_id: UA-110482262-1
    anonymize_ip: true
author:
  name: Anton Karazeev
  avatar: "/assets/images/anton-karazeev.jpg"
  bio: research fellow, developer, photographer
  location: Moscow, Russia
  email: anton.karazeev@gmail.com
  twitter: antonkarazeev
  facebook: anton.karazeev
  linkedin: akarazeev
  youtube: https://www.youtube.com/c/AntonKarazeev
  soundcloud: anton-karazeev
  instagram: akarazeev
  stackoverflow: 5080068/anton-karazeev
  github: akarazeev
  links:
  - label: My Curriculum Vitae
    icon: fas fa-fw fa-link
    url: https://akarazeev.github.io/data/cv.pdf
footer:
  links:
  - label: Email
    icon: fas fa-fw fa-envelope-square
    url: mailto:anton.karazeev@gmail.com
  - label: Twitter
    icon: fab fa-fw fa-twitter-square
    url: https://twitter.com/antonkarazeev
  - label: Facebook
    icon: fab fa-fw fa-facebook-square
    url: https://facebook.com/anton.karazeev
  - label: GitHub
    icon: fab fa-fw fa-github
    url: https://github.com/akarazeev
  - label: YouTube
    icon: fab fa-fw fa-youtube-square
    url: http://youtube.com/c/AntonKarazeev
  - label: Instagram
    icon: fab fa-fw fa-instagram
    url: https://instagram.com/akarazeev
include:
- ".htaccess"
- _pages
exclude:
- "*.sublime-project"
- "*.sublime-workspace"
- vendor
- ".asset-cache"
- ".bundle"
- ".jekyll-assets-cache"
- ".sass-cache"
- assets/js/plugins
- assets/js/_main.js
- assets/js/vendor
- Capfile
- CHANGELOG
- config
- Gemfile
- Gruntfile.js
- gulpfile.js
- LICENSE
- log
- node_modules
- package.json
- Rakefile
- README
- tmp
keep_files:
- ".git"
- ".svn"
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
permalink: "/:categories/:title/"
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
whitelist:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
compress_html:
  clippings: all
  ignore:
    envs: development
